### ISSUE TITLE
JavaScript error on manual reload

### ISSUE THREAD

**Issue by kingfisher77** [lloeki/matterfront#31]
With Mattermost 1.2 we receive this error message in a popup window. It happens after the first reload per cmd-r.

Is this propably related to Mattermost 1.2?

`Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: undefined.
    at ret (/Applications/matterfront.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:146:21)
    at MenuItem.click (/Applications/matterfront.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:58:20)
    at Function.delegate.executeCommand (/Applications/matterfront.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:127:69)`

**Comment by LongLiveCHIEF** [comment]
I don't believe this would be related to the upgrade. Give me a bit to get on a real computer and I will come back and take another look at your error.

**Comment by teetrinkers** [comment]
I can reproduce this using Mattermost 1.2.0-rc1:
- Start Matterfront.
- Hit Cmd-R.
- (Try to) quit Matterfront.

**Comment by daemongh** [comment]
I was able to track this down to the menu code and requiring the `menu.js` file in the app `ready` handler instead of loading it through the HTML seems to fix that problem.
