### ISSUE TITLE
Build fails on OSX Yosemite?

### ISSUE THREAD

**Issue by devvmh** [lloeki/matterfront#42]
Hi, I'm usually pretty good at diagnosing build errors but I'm pretty new to node and I've never used electron before. Do you have any hints as to how to diagnose this build error? I've installed nodejs via Homebrew, and everything is up to date. npm install worked just fine, but when I run `npm run build` I get a `spawn wine ENOENT` error.

I've been going over the npm-debug.log but I really have no clue of where to start. I'm not even sure how to run electron-packager on its own, to see if I can get more helpful error messages. Any hints would help!

And if there's a better spot to post this let me know. Thanks!

```
Airin:matterfront Devin$ node --version
v5.1.0
Airin:matterfront Devin$ npm --version
3.3.12
Airin:matterfront Devin$ npm run build
```

And here's my npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle matterfront@1.0.2~prebuild: matterfront@1.0.2
6 silly lifecycle matterfront@1.0.2~prebuild: no script for prebuild, continuing
7 info lifecycle matterfront@1.0.2~build: matterfront@1.0.2
8 verbose lifecycle matterfront@1.0.2~build: unsafe-perm in lifecycle true
9 verbose lifecycle matterfront@1.0.2~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Devin/Documents/github/matterfront/node_modules/.bin:/Users/Devin/.rvm/gems/ruby-2.2.1/bin:/Users/Devin/.rvm/gems/ruby-2.2.1@global/bin:/Users/Devin/.rvm/rubies/ruby-2.2.1/bin:/usr/local/heroku/bin:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/opt/android-sdk/platform-tools:/Users/Devin/.rvm/bin
10 verbose lifecycle matterfront@1.0.2~build: CWD: /Users/Devin/Documents/github/matterfront
11 silly lifecycle matterfront@1.0.2~build: Args: [ '-c',
11 silly lifecycle   'electron-packager ./src Matterfront --out=dist --ignore=\'^/dist$\' --prune --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id=\'org.matterfront.app\' --app-version=$npm_package_version --helper-bundle-id=\'org.matterfront.app.helper\' --overwrite --icon=resources/mattermost' ]
12 silly lifecycle matterfront@1.0.2~build: Returned: code: 1  signal: null
13 info lifecycle matterfront@1.0.2~build: Failed to exec build script
 14 verbose stack Error: matterfront@1.0.2 build: `electron-packager ./src Matterfront --out=dist --ignore='^/dist$' --prune --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous>(/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid matterfront@1.0.2
16 verbose cwd /Users/Devin/Documents/github/matterfront
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v5.1.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error matterfront@1.0.2 build: `electron-packager ./src Matterfront --out=dist --ignore='^/dist$' --prune --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost`
22 error Exit status 1
23 error Failed at the matterfront@1.0.2 build script 'electron-packager ./src Matterfront --out=dist --ignore='^/dist$' --prune --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the matterfront package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager ./src Matterfront --out=dist --ignore='^/dist$' --prune --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost
23 error You can get their info via:
23 error     npm owner ls matterfront
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by lloeki** [comment]
You need to `brew install wine`

**Comment by devvmh** [comment]
Excellent! After getting wine it worked.

I'm used to Wineskin Winery; I didn't even know Homebrew had wine in it.

It's probably worth mentioning this in the documentation (or pointing to https://github.com/maxogden/electron-packager#building-windows-apps-from-non-windows-platforms), because it would have helped me.

Thanks again!
