### ISSUE TITLE
Error trying to build on El Capitan

### ISSUE THREAD

**Issue by BrianGilbert** [lloeki/matterfront#58]
```
npm run build

> matterfront@1.1.1 build /Users/brian/Downloads/matterfront
> electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost

Downloading electron-v0.35.4-linux-ia32.zip
Downloading electron-v0.35.4-win32-ia32.zip
[============================================>] 100.0% of 40.07 MB (1.56 MB/s)
Packaging app for platform win32 ia32 using electron v0.35.4
spawn wine ENOENT

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/brian/.nvm/versions/node/v5.2.0/bin/node" "/Users/brian/.nvm/versions/node/v5.2.0/bin/npm" "run" "build"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! matterfront@1.1.1 build: `electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the matterfront@1.1.1 build script 'electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the matterfront package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost
npm ERR! You can get their info via:
npm ERR!     npm owner ls matterfront
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brian/Downloads/matterfront/npm-debug.log
19.64s user 12.06s system 35% cpu 1:29.25s total
```

```
$ cat /Users/brian/Downloads/matterfront/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/brian/.nvm/versions/node/v5.2.0/bin/node',
1 verbose cli   '/Users/brian/.nvm/versions/node/v5.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.3.12
3 info using node@v5.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle matterfront@1.1.1~prebuild: matterfront@1.1.1
6 silly lifecycle matterfront@1.1.1~prebuild: no script for prebuild, continuing
7 info lifecycle matterfront@1.1.1~build: matterfront@1.1.1
8 verbose lifecycle matterfront@1.1.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle matterfront@1.1.1~build: PATH: /Users/brian/.nvm/versions/node/v5.2.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/brian/Downloads/matterfront/node_modules/.bin:/Users/brian/.nvm/versions/node/v5.2.0/bin:/Users/brian/.rbenv/shims:/Users/brian/.pip-apps/bin:/Users/brian/.composer/vendor/bin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/brian/.zgen/unixorn/jpb.zshplugin-master/bin:/Users/brian/.zgen/unixorn/git-extra-commands-master:/Users/brian/.zgen/skx/sysadmin-util-master:/Users/brian/.zgen/StackExchange/blackbox-master/bin
10 verbose lifecycle matterfront@1.1.1~build: CWD: /Users/brian/Downloads/matterfront
11 silly lifecycle matterfront@1.1.1~build: Args: [ '-c',
11 silly lifecycle   'electron-packager . Matterfront --out=dist --ignore=\'^/dist$\' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id=\'org.matterfront.app\' --app-version=$npm_package_version --helper-bundle-id=\'org.matterfront.app.helper\' --overwrite --icon=resources/mattermost' ]
12 silly lifecycle matterfront@1.1.1~build: Returned: code: 1  signal: null
13 info lifecycle matterfront@1.1.1~build: Failed to exec build script
14 verbose stack Error: matterfront@1.1.1 build: `electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/brian/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at EventEmitter.emit (events.js:173:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/brian/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at ChildProcess.emit (events.js:173:7)
14 verbose stack     at maybeClose (internal/child_process.js:819:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
15 verbose pkgid matterfront@1.1.1
16 verbose cwd /Users/brian/Downloads/matterfront
17 error Darwin 15.0.0
18 error argv "/Users/brian/.nvm/versions/node/v5.2.0/bin/node" "/Users/brian/.nvm/versions/node/v5.2.0/bin/npm" "run" "build"
19 error node v5.2.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error matterfront@1.1.1 build: `electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost`
22 error Exit status 1
23 error Failed at the matterfront@1.1.1 build script 'electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the matterfront package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . Matterfront --out=dist --ignore='^/dist$' --asar --platform=all --arch=all --version=$npm_package_electronVersion --app-bundle-id='org.matterfront.app' --app-version=$npm_package_version --helper-bundle-id='org.matterfront.app.helper' --overwrite --icon=resources/mattermost
23 error You can get their info via:
23 error     npm owner ls matterfront
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by BrianGilbert** [comment]
Resolved by setting platform and arch in package.json

**Comment by BrianGilbert** [comment]
though the built package just loads a white screen

Looks to be due to https://github.com/lloeki/matterfront/issues/55

**Comment by geekytime** [comment]
I opened #57 to try to resolve the dev-mode/build-mode conflicts caused by 39bbd20c90105bd9d207d908a32cd2b7cd7fc9b8.

**Comment by BrianGilbert** [comment]
now that #57 57 is merged this can be closed I think

**Comment by lloeki** [comment]
Your initial issue was `spawn wine ENOENT`. Install wine when building on a non-Windows OS, as per the docs.

**Comment by BrianGilbert** [comment]
yep, classic case of pebcak..
